### ISSUE TITLE
Encoding question

### ISSUE THREAD

**Issue by babab4757** [rorReddington/SampFuncs-HTTP-Stealer#1]
instead of normal letters im getting these 
![image](https://user-images.githubusercontent.com/80553123/169159023-f1ea172a-1d57-4a9e-9623-59093f15059d.png)

**Comment by rorReddington** [comment]
> instead of normal letters im getting these ![image](https://user-images.githubusercontent.com/80553123/169159023-f1ea172a-1d57-4a9e-9623-59093f15059d.png)

Which version of the SF are you using?

**Comment by roreng** [comment]
> instead of normal letters im getting these ![image](https://user-images.githubusercontent.com/80553123/169159023-f1ea172a-1d57-4a9e-9623-59093f15059d.png)

The output data that you getting is encrypted. You see an encrypted string.

**Comment by rorReddington** [comment]
Updated the sending to the chat. The string is not encrypted.
Attention! Sending to the chat is needed for debugging.

**Comment by roreng** [comment]
I updated a sending to the chat. Now a string is not encrypted.
Attention! Sending to the chat is needed for debugging.
